# Auto-generated by stubgen.py on Thu Jul 30 15:06:01 2026
# -- HAND EDITING NOT ADVISED ---


import InsTask
import g2Task

# Special module-level constant to tell task manager what default subsystem
# these tasks are for
SUBSYS = 'SCEXAO'



####################################################################
# BASE SCEXAO TASKS
####################################################################
#
class SCEXAOTaskError(InsTask.Ins2TaskError):
    pass

class SCEXAOTask(InsTask.Ins2Task):
    """Base SCEXAO task from which SCEXAO device dependent commands tasks
    are derived.
    """
    def __init__(self, cmdname, **kwdargs):
        """_cmdname_ is the command name for this task.
        """

        # This copies all keyword arguments to self.params and does
        # general task initialization
        super(SCEXAOTask, self).__init__('SCEXAO', cmdname, **kwdargs)


####################################################################
# GEN2 SCEXAO TASKS !!!
####################################################################
#

class SCXTaskError(g2Task.g2TaskError):
    pass


class SCXTask(g2Task.g2Task):

    def __init__(self, cmdname, **kwdargs):
        self.parakey = ('SCEXAO', cmdname.upper())
        super(SCXTask, self).__init__(**kwdargs)

    def self_validate(self, nop=None):
        # Populate and validate parameters if we have a parakey defined
        try:
            if self.parakey:
                self.populate(self.parakey)
                self.convert(self.parakey)
                self.validate(self.parakey)
                self.convert(self.parakey, subst_nop=nop)

        except Exception as err:
            raise SCXTaskError("Parameter validation error: %s" % str(err))

    def excecute(self):
        self.self_validate()

        return 0

    #######################################
    # SCX COMMANDS
    #######################################

class check_status_changed(SCXTask):
# enters a loop that exits either when the timer runs out or when the  status variable inputted changes
    def __init__(self, timeout=0, status_var=None):
        super(check_status_changed, self).__init__('check_status_changed', timeout=timeout, status_var=status_var)

    def execute(self):

        self.self_validate()
        self.logger.debug("SCX check_status_changed params<%s>" % str(self.params))

        timeout=self.params["timeout"]
        try:
            timeout = float(timeout)
        except (TypeError, ValueError):
            raise g2Task.g2TaskError(f"command 'check_status_changed' {timeout} must be a number")
        if timeout <= 0 or timeout > 10000:
            raise g2Task.g2TaskError("error: timeout must be greater than 0 and less than or equal to 10,000")

        status_var = self.params["status_var"]
        status_var_val0 = self.fetchOne(status_var).strip()
        status_var_val0 = str(status_var_val0)
        status_var_val = status_var_val0
        while status_var_val == status_var_val0 and timeout > 0:
            # sleep for one second
            self.sleep(1)
            timeout = timeout - 1
            # check status of alias
            status_var_val = self.fetchOne(status_var).strip()
            status_var_val = str(status_var_val)

        if status_var_val.strip() != status_var_val0:
            return 0
        elif timeout == 0:
            raise g2Task.g2TaskError(f"error: timeout in string comparison: {status_var_val0} still hasn't changed")
        else:
            raise g2Task.g2TaskError("critical error in loop")


class check_status(SCXTask):
# This function enters a while loop for the time in seconds given by timeout_counter,an integer escaping only when one (or both) of the conditions are met.
# The third parameter, condition, is a string that has two allowed inputs: 'equals' and 'nonequals'.
# The function will excecute until the condition(s) are satisfied.
# This function supports up to four conditionals, meaning up to two conditional statements.
    def __init__(self, timeout_counter=0, condition=None, status_var1=None, comparison1=None, status_var2=None, comparison2=None):
        super(check_status, self).__init__('check_status', timeout_counter = timeout_counter, condition=condition, status_var1=status_var1, comparison1=comparison1, status_var2=status_var2, comparison2=comparison2)

    def execute(self):

        # print params
        self.self_validate()
        self.logger.debug("SCX check_status params<%s>" % str(self.params))

        # begin parameter checking:

        # check timeount_counter parameter
        timeout_counter = self.params["timeout_counter"]
        try:
            timeout_counter = float(timeout_counter)
        except (TypeError, ValueError):
            raise g2Task.g2TaskError(f"command 'check_status' {timeout_counter} must be a number")
        if timeout_counter <= 0 or timeout_counter > 10000:
            raise g2Task.g2TaskError("error: timeout_counter must be greater than 0 and less than or equal to 10,000")

        # check comparison parameter
        comparison1 = self.params["comparison1"]
        if comparison1 is None:
            raise g2Task.g2TaskError("error: missing comparison")

        # check condition parameter
        condition = self.params["condition"]
        condition = condition.lower()
        if condition is None:
            raise g2Task.g2TaskError("error: missing condition")
        elif condition not in ('equals','nonequals'):
            raise g2Task.g2TaskError(f"error: unsupported parameter on condition: {condition.strip()}")

        # get other params
        comparison2 = self.params["comparison2"]
        status_var1 = self.params["status_var1"]
        status_var2 = self.params["status_var2"]

        # begin function:
        if comparison2 is None:
            status_var1_val = self.fetchOne(status_var1).strip()
            status_var1_val = str(status_var1_val)
            if condition == 'equals':
                while status_var1_val != comparison1 and timeout_counter > 0:
                    # sleep for one second
                    self.sleep(1)
                    timeout_counter = timeout_counter - 1
                    # check status of alias
                    status_var1_val = self.fetchOne(status_var1).strip()
                    status_var1_val = str(status_var1_val)
                if status_var1_val.strip() == comparison1:
                    return 0
                elif timeout_counter == 0:
                    raise g2Task.g2TaskError(f"error: timeout in string comparison: {status_var1_val} still does not equal {comparison1}")
                else:
                    raise g2Task.g2TaskError("critical error in loop")
            elif condition == 'notequals':
                while status_var1_val == comparison1 and timeout_counter > 0:
                    # sleep for one second
                    self.sleep(1)
                    timeout_counter = timeout_counter - 1
                    # check status of alias
                    status_var1_val = self.fetchOne(status_var1).strip()
                    status_var1_val = str(status_var1_val)
                if status_var1_val != comparison1:
                    return 0
                elif timeout_counter == 0:
                    raise g2Task.g2TaskError(f"error: timeout in string comparison: {status_var1_val} still equals {comparison1}")
                else:
                    raise g2Task.g2TaskError("critical error in loop")
        else:
            status_var1_val = self.fetchOne(status_var1).strip()
            status_var2_val = self.fetchOne(status_var2).strip()
            status_var1_val = str(status_var1_val)
            status_var2_val = str(status_var2_val)
            if condition == 'equals':
                while (status_var1_val != comparison1 or status_var2_val != comparison2) and timeout_counter > 0:
                    # sleep for one second
                    self.sleep(1)
                    timeout_counter = timeout_counter - 1
                    # check status of both alias'
                    status_var1_val = self.fetchOne(status_var1).strip()
                    status_var2_val = self.fetchOne(status_var2).strip()
                    status_var1_val = str(status_var1_val)
                    status_var2_val = str(status_var2_val)
                if status_var1_val == comparison1 and status_var2_val == comparison2:
                    return 0
                elif timeout_counter == 0:
                    raise g2Task.g2TaskError(f"error: timeout in string comparison: either {status_var1_val} still does not equal {comparison1} or {status_var2_val} still does not equal {comparison2}")
                else:
                    raise g2Task.g2TaskError("critical error in loop")
            elif condition == 'notequals':
                while (status_var1_val == comparison1 or status_var2_val == comparison2) and timeout_counter > 0:
                    # sleep for one second
                    self.sleep(1)
                    timeout_counter = timeout_counter - 1
                    # check status of both alias'
                    status_var1_val = self.fetchOne(status_var1).strip()
                    status_var2_val = self.fetchOne(status_var2).strip()
                    status_var1_val = str(status_var1_val)
                    status_var2_val = str(status_var2_val)
                if status_var1_val != comparison1 and status_var2_val != comparison2:
                    return 0
                elif timeout_counter == 0:
                    raise g2Task.g2TaskError(f"error: timeout in string comparison: either {status_var1_val} still equals {comparison1} or {status_var2_val} still equals {comparison2}")
                else:
                    raise g2Task.g2TaskError("critical error in loop")

    #######################################
    # END OF GEN2 SCEXAO COMMANDS
    #######################################

    #######################################
    # SCEXAO INSTRUMENT COMMANDS
    #######################################


class Test(SCEXAOTask):
    def __init__(self):
        super(Test, self).__init__('Test')

class Astrogrid(SCEXAOTask):
    def __init__(self, state=None, amplitude=None, mode=None):
        super(Astrogrid, self).__init__('Astrogrid', state=state, amplitude=amplitude, mode=mode)

class Apapane_Pickoff(SCEXAOTask):
    def __init__(self, position=None):
        super(Apapane_Pickoff, self).__init__('Apapane_Pickoff', position=position)

class Charis_Filter(SCEXAOTask):
    def __init__(self, slot=None):
        super(Charis_Filter, self).__init__('Charis_Filter', slot=slot)

class Charis_Pickoff(SCEXAOTask):
    def __init__(self, slot=None):
        super(Charis_Pickoff, self).__init__('Charis_Pickoff', slot=slot)

class Charis_Wollaston(SCEXAOTask):
    def __init__(self, position=None):
        super(Charis_Wollaston, self).__init__('Charis_Wollaston', position=position)

class Dm_Offload(SCEXAOTask):
    def __init__(self, state=None):
        super(Dm_Offload, self).__init__('Dm_Offload', state=state)

class Field_Stop(SCEXAOTask):
    def __init__(self, position=None):
        super(Field_Stop, self).__init__('Field_Stop', position=position)

class Firstpl_Pickoff(SCEXAOTask):
    def __init__(self, position=None):
        super(Firstpl_Pickoff, self).__init__('Firstpl_Pickoff', position=position)

class Fpm(SCEXAOTask):
    def __init__(self, slot=None):
        super(Fpm, self).__init__('Fpm', slot=slot)

class Ircam_Fcs(SCEXAOTask):
    def __init__(self, mode=None):
        super(Ircam_Fcs, self).__init__('Ircam_Fcs', mode=mode)

class Ircam_Filter(SCEXAOTask):
    def __init__(self, slot=None):
        super(Ircam_Filter, self).__init__('Ircam_Filter', slot=slot)

class Ircam_Flc(SCEXAOTask):
    def __init__(self, position=None):
        super(Ircam_Flc, self).__init__('Ircam_Flc', position=position)

class Ircam_Steering(SCEXAOTask):
    def __init__(self, mode=None, a=None, b=None, motion=None):
        super(Ircam_Steering, self).__init__('Ircam_Steering', mode=mode, a=a, b=b, motion=motion)

class Ircam_Wollaston(SCEXAOTask):
    def __init__(self, position=None):
        super(Ircam_Wollaston, self).__init__('Ircam_Wollaston', position=position)

class Loop(SCEXAOTask):
    def __init__(self, state=None):
        super(Loop, self).__init__('Loop', state=state)

class Lyot(SCEXAOTask):
    def __init__(self, slot=None):
        super(Lyot, self).__init__('Lyot', slot=slot)

class Mkids_Pickoff(SCEXAOTask):
    def __init__(self, slot=None):
        super(Mkids_Pickoff, self).__init__('Mkids_Pickoff', slot=slot)

class Oap1(SCEXAOTask):
    def __init__(self, position=None):
        super(Oap1, self).__init__('Oap1', position=position)

class Pywfs_Filter(SCEXAOTask):
    def __init__(self, slot=None):
        super(Pywfs_Filter, self).__init__('Pywfs_Filter', slot=slot)

class Pywfs_Pickoff(SCEXAOTask):
    def __init__(self, slot=None):
        super(Pywfs_Pickoff, self).__init__('Pywfs_Pickoff', slot=slot)

class Pywfs_Gain(SCEXAOTask):
    def __init__(self, em_gain=None):
        super(Pywfs_Gain, self).__init__('Pywfs_Gain', em_gain=em_gain)

class Pywfs_Gain_Reset(SCEXAOTask):
    def __init__(self):
        super(Pywfs_Gain_Reset, self).__init__('Pywfs_Gain_Reset')

class Reach_Pickoff(SCEXAOTask):
    def __init__(self, position=None):
        super(Reach_Pickoff, self).__init__('Reach_Pickoff', position=position)

class Setup_Pywfs(SCEXAOTask):
    def __init__(self, frequency=None, mod_amp=None):
        super(Setup_Pywfs, self).__init__('Setup_Pywfs', frequency=frequency, mod_amp=mod_amp)

class Set_Pywfs_Gain(SCEXAOTask):
    def __init__(self, gain=None):
        super(Set_Pywfs_Gain, self).__init__('Set_Pywfs_Gain', gain=gain)

class Set_Mult_Factor(SCEXAOTask):
    def __init__(self, factor=None):
        super(Set_Mult_Factor, self).__init__('Set_Mult_Factor', factor=factor)

class Set_Modal_Gains(SCEXAOTask):
    def __init__(self, gain=None):
        super(Set_Modal_Gains, self).__init__('Set_Modal_Gains', gain=gain)

class Set_Mode(SCEXAOTask):
    def __init__(self, mode=None):
        super(Set_Mode, self).__init__('Set_Mode', mode=mode)

class Shutdown_Scexao(SCEXAOTask):
    def __init__(self, nop=None):
        super(Shutdown_Scexao, self).__init__('Shutdown_Scexao', nop=nop)

class Sleep(SCEXAOTask):
    def __init__(self, sleep_time=None):
        super(Sleep, self).__init__('Sleep', sleep_time=sleep_time)

class Src_Fib(SCEXAOTask):
    def __init__(self, position=None):
        super(Src_Fib, self).__init__('Src_Fib', position=position)

class Src_Flux(SCEXAOTask):
    def __init__(self, mode=None):
        super(Src_Flux, self).__init__('Src_Flux', mode=mode)

class Startup_Scexao(SCEXAOTask):
    def __init__(self, mode=None):
        super(Startup_Scexao, self).__init__('Startup_Scexao', mode=mode)

class Superk(SCEXAOTask):
    def __init__(self, power=None):
        super(Superk, self).__init__('Superk', power=power)

class Scexao_Dm(SCEXAOTask):
    def __init__(self, state=None):
        super(Scexao_Dm, self).__init__('Scexao_Dm', state=state)
