# Auto-generated by stubgen.py on Mon Jul 20 11:20:01 2026
# -- HAND EDITING NOT ADVISED ---


import g2Task
from Bunch import Bunch

# Special module-level constant to tell task manager what default subsystem
# these tasks are for
SUBSYS = 'SCEXAO'



ddcmd_tbl = {

    'apapane_pickoff':Bunch(fmtstr='EXEC SCEXAO APAPNE_PICKOFF position=%(position)s',
                parakey=('SCEXAO', 'APAPANE_PICKOFF')),
    
    'charis_filter': Bunch(fmtstr='EXEC SCEXAO CHARIS_FILTER SLOT=%(slot)s',
                parakey=('SCEXAO', 'CHARIS_FILTER')),

    'charis_pickoff': Bunch(fmtstr='EXEC SCEXAO CHARIS_PICKOFF SLOT=%(slot)s',
                parakey=('SCEXAO', 'CHARIS_PICKOFF')),

    'charis_wollaston': Bunch(fmtstr='EXEC SCEXAO CHARIS_WOLLASTON POSITION=%(position)s',
                parakey=('SCEXAO', 'CHARIS_WOLLASTON')),

    'field_stop': Bunch(fmtstr='EXEC SCEXAO FIELD_STOP POSITION=%(position)s',
                parakey=('SCEXAO', 'FIELD_STOP')),

    'firstpl_pickoff': Bunch(fmtstr='EXEC SCEXAO FIRSTPL_PICKOFF POSITION=%(position)s',
                parakey=('SCEXAO', 'FIRSTPL_PICKOFF')),

    'fpm': Bunch(fmtstr='EXEC SCEXAO FPM SLOT=%(slot)s',
                parakey=('SCEXAO', 'FPM')),

    'ircam_fcs': Bunch(fmtstr='EXEC SCEXAO IRCAM_FCS MODE=%(mode)s',
                parakey=('SCEXAO', 'IRCAM_FCS')),

    'ircam_filter': Bunch(fmtstr='EXEC SCEXAO IRCAM_FILTER SLOT=%(slot)s',
                parakey=('SCEXAO', 'IRCAM_FILTER')),

    'ircam_steering': Bunch(fmtstr='EXEC SCEXAO IRCAM_STEERING MODE=%(mode)s A=%(a)s B=%(b)s MOTION=%(motion)s',
                parakey=('SCEXAO', 'IRCAM_STEERING')),

    'ircam_wollaston': Bunch(fmtstr='EXEC SCEXAO IRCAM_WOLLASTON POSITION=%(position)s',
                parakey=('SCEXAO', 'IRCAM_WOLLASTON')),

    'lyot': Bunch(fmtstr='EXEC SCEXAO LYOT SLOT=%(slot)s',
                parakey=('SCEXAO', 'LYOT')),

    'mkids_pickoff': Bunch(fmtstr='EXEC SCEXAO MKIDS_PICKOFF SLOT=%(slot)s',
                parakey=('SCEXAO', 'MKIDS_PICKOFF')),

    'pywfs_pickoff': Bunch(fmtstr='EXEC SCEXAO PYWFS_PICKOFF SLOT=%(slot)s',
                parakey=('SCEXAO', 'PYWFS_PICKOFF')),

    'pywfs_filter': Bunch(fmtstr='EXEC SCEXAO PYWFS_FILTER SLOT=%(slot)s',
                parakey=('SCEXAO', 'PYWFS_FILTER')),

    'reach_pickoff': Bunch(fmtstr='EXEC SCEXAO REACH_PICKOFF POSITION=%(position)s',
                parakey=('SCEXAO', 'REACH_PICKOFF')),

    'sleep': Bunch(fmtstr='EXEC SCEXAO SLEEP SLEEP_TIME=%(sleep_time)s',
                parakey=('SCEXAO', 'SLEEP')),

    'src_fib': Bunch(fmtstr='EXEC SCEXAO SRC_FIB POSITION=%(position)s',
                parakey=('SCEXAO', 'SRC_FIB')),

    'src_flux': Bunch(fmtstr='EXEC SCEXAO SRC_FLUX MODE=%(mode)s',
                parakey=('SCEXAO', 'SRC_FLUX')),

    'startup_scexao': Bunch(fmtstr='EXEC SCEXAO STARTUP_SCEXAO MODE=%(mode)s',
                parakey=('SCEXAO', 'STARTUP_SCEXAO')),

    'shutdown_scexao': Bunch(fmtstr='EXEC SCEXAO SHUTDOWN_SCEXAO NOP=%(NOP)s',
                parakey=('SCEXAO', 'SHUTDOWN_SCEXAO')),

    'set_mode': Bunch(fmtstr='EXEC SCEXAO SET_MODE MODE=%(mode)s',
                parakey=('SCEXAO', 'SET_MODE')),

    'setup_pywfs': Bunch(fmtstr='EXEC SCEXAO SETUP_PYWFS FREQUENCY=%(frequency)s' 'MOD_AMP=%(mod_amp)s',
                parakey=('SCEXAO', 'SETUP_PYWFS')),

    'superk': Bunch(fmtstr='EXEC SCEXAO SUPERK POWER=%(power)s',
                parakey=('SCEXAO', 'SUPERK')),
    }
    

####################################################################
# BASE SCEXAO TASKS
####################################################################
#
class SCEXAOTaskError(g2Task.g2TaskError):
    pass

class SCEXAOTask(g2Task.INSintTask):
    """Base SCEXAO task from which SCEXAO device dependent commands tasks
    are derived.
    """
    def __init__(self, ddcmd_key, **kwdargs):
        """_ddcmd_key_ is a key to look up the details of our formatting,
        parameter checking, etc.
        """

        ddcmd = ddcmd_tbl[ddcmd_key.lower()]

        # This copies all keyword arguments to self.params and does
        # general task initialization
        super(SCEXAOTask, self).__init__('SCEXAO', ddcmd.fmtstr,
                                        ddcmd.parakey, **kwdargs)

    #######################################
    # SCEXAO INSTRUMENT COMMANDS
    #######################################

class Apapane_Pickoff(SCEXAOTask):
    def __init__(self, position=None):
        super(Apapane_Pickoff, self).__init__('Apapane_Pickoff', position=position)

class Charis_Filter(SCEXAOTask):
    def __init__(self, slot=None):
        super(Charis_Filter, self).__init__('Charis_Filter', slot=slot)

class Charis_Pickoff(SCEXAOTask):
    def __init__(self, slot=None):
        super(Charis_Pickoff, self).__init__('Charis_Pickoff', slot=slot)

class Charis_Wollaston(SCEXAOTask):
    def __init__(self, position=None):
        super(Charis_Wollaston, self).__init__('Charis_Wollaston', position=position)

class Field_Stop(SCEXAOTask):
    def __init__(self, position=None):
        super(Field_Stop, self).__init__('Field_Stop', position=position)

class Firstpl_Pickoff(SCEXAOTask):
    def __init__(self, position=None):
        super(Firstpl_Pickoff, self).__init__('Firstpl_Pickoff', position=position)

class Fpm(SCEXAOTask):
    def __init__(self, slot=None):
        super(Fpm, self).__init__('Fpm', slot=slot)

class Ircam_Fcs(SCEXAOTask):
    def __init__(self, mode=None):
        super(Ircam_Fcs, self).__init__('Ircam_Fcs', mode=mode)

class Ircam_Filter(SCEXAOTask):
    def __init__(self, slot=None):
        super(Ircam_Filter, self).__init__('Ircam_Filter', slot=slot)

class Ircam_Steering(SCEXAOTask):
    def __init__(self, mode=None, a=None, b=None, motion=None):
        super(Ircam_Steering, self).__init__('Ircam_Steering', mode=mode, a=a, b=b, motion=motion)

class Ircam_Wollaston(SCEXAOTask):
    def __init__(self, position=None):
        super(Ircam_Wollaston, self).__init__('Ircam_Wollaston', position=position)

class Lyot(SCEXAOTask):
    def __init__(self, slot=None):
        super(Lyot, self).__init__('Lyot', slot=slot)

class Mkids_Pickoff(SCEXAOTask):
    def __init__(self, slot=None):
        super(Mkids_Pickoff, self).__init__('Mkids_Pickoff', slot=slot)

class PYWFS_Pickoff(SCEXAOTask):
    def __init__(self, slot=None):
        super(PYWFS_Pickoff, self).__init__('PYWFS_Pickoff', slot=slot)

class PYWFS_Filter(SCEXAOTask):
    def __init__(self, slot=None):
        super(PYWFS_Filter, self).__init__('PYWFS_Filter', slot=slot)

class Reach_Pickoff(SCEXAOTask):
    def __init__(self, position=None):
        super(Reach_Pickoff, self).__init__('Reach_Pickoff', position=position)

class Sleep(SCEXAOTask):
    def __init__(self, sleep_time=None):
        super(Sleep, self).__init__('Sleep', sleep_time=sleep_time)

class Src_Fib(SCEXAOTask):
    def __init__(self, position=None):
        super(Src_Fib, self).__init__('Src_Fib', position=position)

class Src_Flux(SCEXAOTask):
    def __init__(self, mode=None):
        super(Src_Flux, self).__init__('Src_Flux', mode=mode)

class Startup_Scexao(SCEXAOTask):
    def __init__(self, mode=None):
        super(Startup_Scexao, self).__init__('Startup_Scexao', mode=mode)

class Shutdown_Scexao(SCEXAOTask):
    def __init__(self, NOP=None):
        super(Shutdown_Scexao, self).__init__('Shutdown_Scexao', NOP=NOP)

class Set_Mode(SCEXAOTask):
    def __init__(self, mode=None):
        super(Set_Mode, self).__init__('Set_Mode', mode=mode)

class Setup_PYWFS(SCEXAOTask):
    def __init__(self, frequency=None, mod_amp=None):
        super(Setup_PYWFS, self).__init__('Setup_PYWFS', frequency=frequency, mod_amp=mod_amp)

class Superk(SCEXAOTask):
    def __init__(self, power=None):
        super(Src_Fib, self).__init__('Src_Fib', power=power)
