# Auto-generated by stubgen.py on Thu Jul 30 15:06:01 2026
# -- HAND EDITING NOT ADVISED ---


import InsTask
import g2Task

# Special module-level constant to tell task manager what default subsystem
# these tasks are for
SUBSYS = 'SCEXAO'



####################################################################
# BASE SCEXAO TASKS
####################################################################
#
class SCEXAOTaskError(InsTask.Ins2TaskError):
    pass

class SCEXAOTask(InsTask.Ins2Task):
    """Base SCEXAO task from which SCEXAO device dependent commands tasks
    are derived.
    """
    def __init__(self, cmdname, **kwdargs):
        """_cmdname_ is the command name for this task.
        """

        # This copies all keyword arguments to self.params and does
        # general task initialization
        super(SCEXAOTask, self).__init__('SCEXAO', cmdname, **kwdargs)

class SCXTaskError(g2Task.g2TaskError):
    pass


####################################################################
# GEN2 SCEXAO TASKS !!!
####################################################################
#

class SCXTask(g2Task.g2Task):

    def __init__(self, cmdname, **kwdargs):
        self.parakey = ('SCX', ddcmd_key.upper())
        super(SCXTask, self).__init__('SCX', cmdname, **kwdargs)

    def self_validate(self, nop=None):
        # Populate and validate parameters if we have a parakey defined
        try:
            if self.parakey:
                self.populate(self.parakey)
                self.convert(self.parakey)
                self.validate(self.parakey)

                # Announce full command string
                try:
                    command_string = self.param2str(self.parakey)
                    self.setMy(cmd_str=command_string)
                except Exception as err:
                    self.logger.error("Error setting command_string: %s" % str(err))

                self.convert(self.parakey, subst_nop=nop)

        except Exception as err:
            raise SCXTaskError("Parameter validation error: %s" % str(err))

    def excecute(self):
        self.self_validate()

        return 0

    #######################################
    # SCX COMMANDS
    #######################################

class check_status(SCXTask):
# this function enters a while loop for the time in seconds given by timeout_counter,an integer
# escaping only when one (or both) of the conditions are met.
# the third parameter, condition, is a string that has two allowed inputs: 'equals' and 'nonequals'.
# The function will excecute until the condition(s) are satisfied
# This function supports up to four conditionals, meaning up to two conditional statements
    def __init__(self, timeout_counter=0, condition=None, status_var1=None, comparison1=None, status_var2=None, comparison2=None):
        super(CHECK_STATUS, self).__init__('CHECK_STATUS', timeout_counter = timeout_counter, condition=condition, status_var1=status_var1, comparison1=comparison1, status_var2=status_var2, comparison2=comparison2

    def execute(self):

        # print params
        self.self_validate()
        self.logger.debug("SCX check_status params<%s>" self.params)

        # begin parameter checking:

        # check timeount_counter parameter
        timeout_counter = self.params[timeout_counter]
        try:
            timeout_counter = float(timeout_counter)
        except (TypeError, ValueError):
            raise f"command 'check_status_local' {timeout_counter} must be a number"
            return None
        if timeout_counter <= 0 or timeout_counter > 10000:
            raise "error: timeout_counter must be greater than 0 and less than or equal to 10,000"
            return None

        # check comparison parameter
        comparison1 = self.params[comparison1]
        if comparison1 is None:
            raise "error: missing comparison"
            return None

        # check condition parameter
        condition = self.params[condition]
        condition = condition.lower()
        if condition is None:
            raise "error: missing condition"
            return None
        elif condition not in ('equals','nonequals'):
            raise f"error: unsupported parameter on condition: {condition}"

        # get other params
        comparison2 = self.params[comparison2]
        status_var1 = fetchOne(self, self.params[status_var1])
        status_var2 = fetchOne(self, self.params[status_var2])

        # begin function:
        if comparison2 is None:
            if condition == 'equals':
                while status_var1 != comparison1 and timeout_counter > 0:
                    # sleep for one second
                    self.sleep(1)
                    timeout_counter = timeout_counter - 1
                    # check status of alias
                    status_var1 = fetchOne(self, self.params[status_var1])
                if status_var1 == comparison1:
                    return "Loop exited: condition satisfied"
                elif timeout_counter == 0:
                    raise f"error: timeout in string comparison: {status_var1} still does not equal {comparison1}"
                    return None
                else:
                    raise "critical error in loop"
                    return None
            elif condition == 'notequals':
                while status_var1 == comparison1 and timeout_counter > 0:
                    # sleep for one second
                    self.sleep(1)
                    timeout_counter = timeout_counter - 1
                    # check status of alias
                    status_var1 = fetchOne(self, self.params[status_var1])
                if status_var1 != comparison1:
                    return "Loop exited: condition satisfied"
                elif timeout_counter == 0:
                    raise f"error: timeout in string comparison: {status_var1} still equals {comparison1}"
                    return None
                else:
                    raise "critical error in loop"
                    return None
        else:
            if condition == 'equals':
                while (status_var1 != comparison1 or status_var2 != comparison2) and timeout_counter > 0:
                    # sleep for one second
                    self.sleep(1)
                    timeout_counter = timeout_counter - 1
                    # check status of both alias'
                    status_var1 = fetchOne(self, self.params[status_var1])
                    status_var2 = fetchOne(self, self.params[status_var2])
                if status_var1 == comparison1 and status_var2 == comparison2:
                    return "Loop exited: conditions satisfied"
                elif timeout_counter == 0:
                    raise f"error: timeout in string comparison: either {status_var1} still does not equal {comparison1} or {status_var2} still does not equal {comparison2}"
                    return None
                else:
                    raise "critical error in loop"
                    return None
            elif condition == 'notequals':
                while (status_var1 == comparison1 or status_var2 == comparison2) and timeout_counter > 0:
                    # sleep for one second
                    self.sleep(1)
                    timeout_counter = timeout_counter - 1
                    # check status of both alias'
                    status_var1 = fetchOne(self, self.params[status_var1])
                    status_var2 = fetchOne(self, self.params[status_var2])
                if status_var1 != comparison1 and status_var2 != comparison2:
                    return "Loop exited: condition satisfied"
                elif timeout_counter == 0:
                    raise f"error: timeout in string comparison: either {status_var1} still equals {comparison1} or {status_var2} still equals {comparison2}"
                    return None
                else:
                    raise "critical error in loop"
                    return None

    ###
    # End of Gen2 SCX Commands
    ###

    #######################################
    # SCEXAO INSTRUMENT COMMANDS
    #######################################


class Test(SCEXAOTask):
    def __init__(self):
        super(Test, self).__init__('Test')

class Astrogrid(SCEXAOTask):
    def __init__(self, state=None, amplitude=None, mode=None):
        super(Astrogrid, self).__init__('Astrogrid', state=state, amplitude=amplitude, mode=mode)

class Apapane_Pickoff(SCEXAOTask):
    def __init__(self, position=None):
        super(Apapane_Pickoff, self).__init__('Apapane_Pickoff', position=position)

class Charis_Filter(SCEXAOTask):
    def __init__(self, slot=None):
        super(Charis_Filter, self).__init__('Charis_Filter', slot=slot)

class Charis_Pickoff(SCEXAOTask):
    def __init__(self, slot=None):
        super(Charis_Pickoff, self).__init__('Charis_Pickoff', slot=slot)

class Charis_Wollaston(SCEXAOTask):
    def __init__(self, position=None):
        super(Charis_Wollaston, self).__init__('Charis_Wollaston', position=position)

class Field_Stop(SCEXAOTask):
    def __init__(self, position=None):
        super(Field_Stop, self).__init__('Field_Stop', position=position)

class Firstpl_Pickoff(SCEXAOTask):
    def __init__(self, position=None):
        super(Firstpl_Pickoff, self).__init__('Firstpl_Pickoff', position=position)

class Fpm(SCEXAOTask):
    def __init__(self, slot=None):
        super(Fpm, self).__init__('Fpm', slot=slot)

class Ircam_Fcs(SCEXAOTask):
    def __init__(self, mode=None):
        super(Ircam_Fcs, self).__init__('Ircam_Fcs', mode=mode)

class Ircam_Filter(SCEXAOTask):
    def __init__(self, slot=None):
        super(Ircam_Filter, self).__init__('Ircam_Filter', slot=slot)

class Ircam_Flc(SCEXAOTask):
    def __init__(self, position=None):
        super(Ircam_Flc, self).__init__('Ircam_Flc', position=position)

class Ircam_Steering(SCEXAOTask):
    def __init__(self, mode=None, a=None, b=None, motion=None):
        super(Ircam_Steering, self).__init__('Ircam_Steering', mode=mode, a=a, b=b, motion=motion)

class Ircam_Wollaston(SCEXAOTask):
    def __init__(self, position=None):
        super(Ircam_Wollaston, self).__init__('Ircam_Wollaston', position=position)

class Lyot(SCEXAOTask):
    def __init__(self, slot=None):
        super(Lyot, self).__init__('Lyot', slot=slot)

class Mkids_Pickoff(SCEXAOTask):
    def __init__(self, slot=None):
        super(Mkids_Pickoff, self).__init__('Mkids_Pickoff', slot=slot)

class Oap1(SCEXAOTask):
    def __init__(self, position=None):
        super(Oap1, self).__init__('Oap1', position=position)

class Pywfs_Filter(SCEXAOTask):
    def __init__(self, slot=None):
        super(Pywfs_Filter, self).__init__('Pywfs_Filter', slot=slot)

class Pywfs_Pickoff(SCEXAOTask):
    def __init__(self, slot=None):
        super(Pywfs_Pickoff, self).__init__('Pywfs_Pickoff', slot=slot)

class Pywfs_Gain(SCEXAOTask):
    def __init__(self, em_gain=None):
        super(Pywfs_Gain, self).__init__('Pywfs_Gain', em_gain=em_gain)

class Pywfs_Gain_Reset(SCEXAOTask):
    def __init__(self):
        super(Pywfs_Gain_Reset, self).__init__('Pywfs_Gain_Reset')

class Reach_Pickoff(SCEXAOTask):
    def __init__(self, position=None):
        super(Reach_Pickoff, self).__init__('Reach_Pickoff', position=position)

class Setup_Pywfs(SCEXAOTask):
    def __init__(self, frequency=None, mod_amp=None):
        super(Setup_Pywfs, self).__init__('Setup_Pywfs', frequency=frequency, mod_amp=mod_amp)

class Set_Mode(SCEXAOTask):
    def __init__(self, mode=None):
        super(Set_Mode, self).__init__('Set_Mode', mode=mode)

class Shutdown_Scexao(SCEXAOTask):
    def __init__(self, nop=None):
        super(Shutdown_Scexao, self).__init__('Shutdown_Scexao', nop=nop)

class Sleep(SCEXAOTask):
    def __init__(self, sleep_time=None):
        super(Sleep, self).__init__('Sleep', sleep_time=sleep_time)

class Src_Fib(SCEXAOTask):
    def __init__(self, position=None):
        super(Src_Fib, self).__init__('Src_Fib', position=position)

class Src_Flux(SCEXAOTask):
    def __init__(self, mode=None):
        super(Src_Flux, self).__init__('Src_Flux', mode=mode)

class Startup_Scexao(SCEXAOTask):
    def __init__(self, mode=None):
        super(Startup_Scexao, self).__init__('Startup_Scexao', mode=mode)

class Superk(SCEXAOTask):
    def __init__(self, power=None):
        super(Superk, self).__init__('Superk', power=power)

class Scexao_Dm(SCEXAOTask):
    def __init__(self, state=None):
        super(Scexao_Dm, self).__init__('Scexao_Dm', state=state)
