# Auto-generated by stubgen.py on Mon Jul 20 11:21:31 2026
# -- HAND EDITING NOT ADVISED ---


unimplemented_res = 2


    def charis_filter(self, slot=None):
        self.logger.error("command 'charis_filter' not yet implemented")
        res = unimplemented_res
        return res

    def charis_pickoff(self, slot=None):
        self.logger.error("command 'charis_pickoff' not yet implemented")
        res = unimplemented_res
        return res

    def charis_wollaston(self, position=None):
        self.logger.error("command 'charis_wollaston' not yet implemented")
        res = unimplemented_res
        return res

    def field_stop(self, position=None):
        self.logger.error("command 'field_stop' not yet implemented")
        res = unimplemented_res
        return res

    def fpm(self, slot=None):
        self.logger.error("command 'fpm' not yet implemented")
        res = unimplemented_res
        return res

    def ircam_filter(self, slot=None):
        self.logger.error("command 'ircam_filter' not yet implemented")
        res = unimplemented_res
        return res

    def ircam_flc(self, position=None):
        self.logger.error("command 'ircam_flc' not yet implemented")
        res = unimplemented_res
        return res

    def ircam_steering(self, mode=None, a=None, b=None, motion=None):
        self.logger.error("command 'ircam_steering' not yet implemented")
        res = unimplemented_res
        return res

    def ircam_wollaston(self, position=None):
        self.logger.error("command 'ircam_wollaston' not yet implemented")
        res = unimplemented_res
        return res

    def lyot(self, slot=None):
        self.logger.error("command 'lyot' not yet implemented")
        res = unimplemented_res
        return res

    def mkids_pickoff(self, slot=None):
        self.logger.error("command 'mkids_pickoff' not yet implemented")
        res = unimplemented_res
        return res

    def sleep(self, sleep_time=None):
        self.logger.error("command 'sleep' not yet implemented")
        res = unimplemented_res
        return res

    def src_fib(self, position=None):
        self.logger.error("command 'src_fib' not yet implemented")
        res = unimplemented_res
        return res

