:Header
    OBE_ID=SCEXAO
    OBE_MODE=INFRA_RED
    COMMAND=APAPANE_PICKOFF
    Script_ID=INFRA_RED09
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/10

:Parameter
    POSITION=OUT
    *POSITION=IN,OUT

:Command
:start

# local function
def execute_command(comparison){
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Changing...";
    EXEC SCEXAO APAPANE_PICKOFF SLOT=$SLOT;
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.APAPANE.PKO" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Position= !SCX.APAPANE.PKO";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="Apapane Pickoff Position Change" ObsInfo2=Clear ObsInfo3="CMD: Position=$POSITION" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$SLOT" == "IN"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="IN")

    *ELIF "$SLOT" == "OUT"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="OUT")

    *ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
