:Header
    OBE_ID=SCEXAO
    OBE_MODE=INFRA_RED
    COMMAND=CHARIS_PICKOFF
    Script_ID=INFRA_RED02
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/06

:Parameter
    SLOT=1.12UMLP
    *SLOT=T10R90,T90R10,ARWINDOW,MIRROR,1.12UMLP,1.35UMLP,1.88UMLP

:Command
:start

# import
from "SCEXAO_Helpers" import strip
# status with no following spaces
asn mystatus = @strip("!SCX.CHARIS.PKO")

# local function
def execute_command(comparison){
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Changing...";
    EXEC SCEXAO CHARIS_PICKOFF SLOT=$SLOT;
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.CHARIS.PKO" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: Slot= !SCX.CHARIS.PKO";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="CHARIS Pickoff Slot Change" ObsInfo2=Clear ObsInfo3="CMD: Slot=$SLOT" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    IF "$SLOT" == "T10R90"
        IF @mystatus == "T10/R90"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="T10/R90")
        ENDIF

    ELIF "$SLOT" == "T90R10"
        IF @mystatus == "T90/R10"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="T90/R10")
        ENDIF

    ELIF "$SLOT" == "ARWINDOW"
        IF @mystatus == "AR window"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="AR window")
        ENDIF

    ELIF "$SLOT" == "MIRROR"
        IF @mystatus == "Gold mirror"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="Gold mirror")
        ENDIF

    ELIF "$SLOT" == "1.12UMLP"
        IF @mystatus == "1.12 um LP"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="1.12 um LP")
        ENDIF

    ELIF "$SLOT" == "1.35UMLP"
        IF @mystatus == "1.35 um LP"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="1.35 um LP")
        ENDIF

    ELIF "$SLOT" == "1.88UMLP"
        IF @mystatus == "1.88 um LP"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="1.88 um LP")
        ENDIF

    ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
