:Header
    OBE_ID=SCEXAO
    OBE_MODE=INFRA_RED
    COMMAND=CHARIS_FILTER
    Script_ID=INFRA_RED03
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/06

:Parameter
    SLOT=OUT
    *SLOT=J,H,K,OUT

###############################
# WITHOUT STATUS ALIAS
###############################

:Command
:start

# local function
def execute_command(comparison){
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Changing...";

    EXEC SCEXAO CHARIS_FILTER SLOT=$SLOT;

#    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="status alias" COMPARISON1="@comparison";
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: Slot= !status alias";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="CHARIS FILTER Slot Change" ObsInfo2=Clear ObsInfo3="CMD: Slot=$SLOT" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$SLOT" == "J"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="j")

    *ELIF "$SLOT" == "H"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="h")

    *ELIF "$SLOT" == "K"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="k")

    *ELIF "$SLOT" == "OUT"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="out")

    *ENDIF
:main_end

#Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
