:Header
    OBE_ID=SCEXAO
    OBE_MODE=INFRA_RED
    COMMAND=CHARIS_PICKOFF
    Script_ID=INFRA_RED02
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/06

:Parameter
    SLOT=1.12UMLP
    *SLOT=T10R90,T90R10,ARWINDOW,MIRROR,1.12UMLP,1.35UMLP,1.88UMLP

:Command
:start

# local function
def execute_command(comparison){
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Changing...";
    EXEC SCEXAO CHARIS_PICKOFF SLOT=$SLOT;
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.CHARIS.PKO" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: Slot= !SCX.CHARIS.PKO";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="CHARIS Pickoff Slot Change" ObsInfo2=Clear ObsInfo3="CMD: Slot=$SLOT" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$SLOT" == "T10R90"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="T10/R90")

    *ELIF "$SLOT" == "T90R10"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="T90/R10")

    *ELIF "$SLOT" == "ARWINDOW"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="AR window")

    *ELIF "$SLOT" == "MIRROR"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="Gold mirror")

    *ELIF "$SLOT" == "1.12UMLP"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="1.12 um LP")

    *ELIF "$SLOT" == "1.35UMLP"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="1.35 um LP")

    *ELIF "$SLOT" == "1.88UMLP"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="1.88 um LP")

    *ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
