:Header
    OBE_ID=SCEXAO
    OBE_MODE=INFRA_RED
    COMMAND=EM_GAIN_RESET
    Script_ID=INFRA_RED15
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/10

:Parameter

:Command
:start

################################
# UNIMPLEMENTED COMMAND
################################


# local function
def execute_command(comparison){
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Resetting...";
    EXEC SCEXAO EM_GAIN_RESET;
#    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="status aliasL" COMPARISON1="@comparison";
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: status alias";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="EM Gain Reset" ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;

:main_start

    # must assign to variable to excetue local function
    # unimplemented command
    asn why_do_I_exist = @execute_command(comparison="none")

:main_end

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
