:Header
    OBE_ID=SCEXAO
    OBE_MODE=INFRA_RED
    COMMAND=FPM
    Script_ID=INFRA_RED05
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/06

:Parameter
    SLOT=OPEN
    *SLOT=VVC,OPEN,LYOT78,LYOT92,LYOT113,LYOT139,LYOT165,LYOT198,LYOT228,LYOT262,LYOT310

:Command
:start

# import
from "SCEXAO_Helpers" import strip
# status with no following spaces
asn mystatus = @strip("!SCX.FPM")

# local function
def execute_command(comparison){
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Changing...";
    EXEC SCEXAO FPM SLOT=$SLOT;
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.FPM" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: Slot= !SCX.FPM";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="Coronograph FPM Slot Change" ObsInfo2=Clear ObsInfo3="CMD: Slot=$SLOT" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    IF "$SLOT" == "VVC"
        IF @mystatus == "Vect vortex msk"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="Vect vortex msk")
        ENDIF

    ELIF "$SLOT" == "OPEN"
        IF @mystatus == "OPEN"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="OPEN")
        ENDIF

    ELIF "$SLOT" == "LYOT78"
        IF @mystatus == "Occulter 78mas"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="Occulter 78mas")
        ENDIF

    ELIF "$SLOT" == "LYOT92"
        IF @mystatus == "Occulter 92mas"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="Occulter 92mas")
        ENDIF

    ELIF "$SLOT" == "LYOT113"
        IF @mystatus == "Occulter 113mas"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="Occulter 113mas")
        ENDIF

    ELIF "$SLOT" == "LYOT139"
        IF @mystatus == "Occulter 139mas"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="Occulter 139mas")
        ENDIF

    ELIF "$SLOT" == "LYOT165"
        IF @mystatus == "Occulter 165mas"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="Occulter 165mas")
        ENDIF

    ELIF "$SLOT" == "LYOT198"
        IF @mystatus == "Occulter 198mas"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="Occulter 198mas")
        ENDIF

    ELIF "$SLOT" == "LYOT228"
        IF @mystatus == "Occulter 228mas"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="Occulter 228mas")
        ENDIF

    ELIF "$SLOT" == "LYOT262"
        IF @mystatus == "Occulter 262mas"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="Occulter 262mas")
        ENDIF

    ELIF "$SLOT" == "LYOT310"
        IF @mystatus == "Occulter 310mas"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="Occulter 310mas")
        ENDIF

    ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
