:Header
    OBE_ID=SCEXAO
    OBE_MODE=INFRA_RED
    COMMAND=FPM
    Script_ID=INFRA_RED05
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/06

:Parameter
    SLOT=OPEN
    *SLOT=VVC,OPEN,LYOT78,LYOT92,LYOT113,LYOT139,LYOT165,LYOT198,LYOT228,LYOT262,LYOT310

:Command
:start

# local function
def execute_command(comparison){
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Changing...";
    EXEC SCEXAO FPM SLOT=$SLOT;
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.FPM" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Slot= !SCX.FPM";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="Coronograph FPM Slot Change" ObsInfo2=Clear ObsInfo3="CMD: Slot=$SLOT" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$SLOT" == "VVC"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="Vect vortex msk")

    *ELIF "$SLOT" == "OPEN"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="Open")

    *ELIF "$SLOT" == "LYOT78"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="Occulter 78mas")

    *ELIF "$SLOT" == "LYOT92"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="Occulter 92mas")

    *ELIF "$SLOT" == "LYOT113"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="Occulter 113mas")

    *ELIF "$SLOT" == "LYOT139"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="Occulter 139mas")

    *ELIF "$SLOT" == "LYOT165"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="Occulter 165mas")

    *ELIF "$SLOT" == "LYOT198"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="Occulter 198mas")

    *ELIF "$SLOT" == "LYOT228"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="Occulter 228mas")

    *ELIF "$SLOT" == "LYOT262"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="Occulter 262mas")

    *ELIF "$SLOT" == "LYOT310"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="Occulter 310mas")

    *ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
