:Header
    OBE_ID=SCEXAO
    OBE_MODE=INFRA_RED
    COMMAND=IRCAM_STEERING
    Script_ID=INFRA_RED06
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/10

:Parameter
    MODE=ONAXIS
    *MODE=ONAXIS, PALILAXY, PALILAANGLE, SKYANGLE
    A=0
    B=0
    MOTION=ABS
    *MOTION=ABS,REL

###############################
# WITHOUT STATUS ALIAS
###############################

:Command
:start

# local function
def execute_command(comparison){
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Changing...";

    EXEC SCEXAO IRCAM_STEERING MODE=$MODE A=$A B=$B MOTION=$MOTION;

# for now no status alias avaliable
#    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="status alias" COMPARISON1="@comparison";
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;

    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: Mode= $MODE" ObsInfo4="a=$A, b=$B" ObsInfo5="Motion=$MOTION";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="IRcam Steering Mode Change" ObsInfo2=Clear ObsInfo3="CMD: Mode=$MODE" ObsInfo4="a=$A, b=$B" ObsInfo5="Motion=$MOTION";

:main_start
    IF "$MODE" == "ONAXIS"

        # must assign to variable to excetue local function
        # 'none' to be filled in with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    ELIF "$MODE" == "PALILAXY"

        # must assign to variable to excetue local function
        # 'none' to be filled in with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    ELIF "$MODE" == "PALILAANGLE"

        # must assign to variable to excetue local function
        # 'none' to be filled in with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    ELIF "$MODE" == "SKYANGLE"

        # must assign to variable to excetue local function
        # 'none' to be filled in with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    ENDIF
:main_end

#Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
