:Header
    OBE_ID=SCEXAO
    OBE_MODE=INFRA_RED
    COMMAND=IRCAM_WOLLASTON
    Script_ID=INFRA_RED12
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/10

:Parameter
    POSITION=OUT
    *POSITION=IN,OUT

:Command
:start

# import
from "SCEXAO_Helpers" import strip
# status with no following spaces
asn mystatus = @strip("!SCX.IRCAM.WOL")

# local function
def execute_command(comparison){
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Changing...";
    EXEC SCEXAO IRCAM_WOLLASTON POSITION=$POSITION;
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.IRCAM.WOL" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: Position= !SCX.IRCAM.WOL";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="IRCam Wollaston Position Change" ObsInfo2=Clear ObsInfo3="CMD: POSITION=$POSITION" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    IF @mystatus == "$POSITION"
        Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
        Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
    ELSE
        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="$POSITION")
    ENDIF

:main_end

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
