:Header
    OBE_ID=SCEXAO
    OBE_MODE=INFRA_RED
    COMMAND=IRCAM_FILTER
    Script_ID=INFRA_RED07
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/10

:Parameter
    SLOT=OPEN
    *SLOT=OPEN,Y,1550NM25NM,1550NM50NM,J,H

:Command
:start

# import
from "SCEXAO_Helpers" import strip
# status with no following spaces
asn mystatus = @strip("!SCX.IRCAM.FLT")

# local function
def execute_command(comparison){
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Changing...";
    EXEC SCEXAO IRCAM_FILTER SLOT=$SLOT;
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.IRCAM.FLT" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: Slot= !SCX.IRCAM.FLT";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="IRCam Filter Slot Change" ObsInfo2=Clear ObsInfo3="CMD: Slot=$SLOT" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    IF "$SLOT" == "OPEN"
        IF @mystatus == "OPEN"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="OPEN")
        ENDIF

    ELIF "$SLOT" == "Y"
        IF @mystatus == "y-band"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="y-band")
        ENDIF

    ELIF "$SLOT" == "1550NM25NM"
        IF @mystatus == "1550nm, 25nm BW"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="1550nm, 25nm BW")
        ENDIF

    ELIF "$SLOT" == "1550NM50NM"
        IF @mystatus == "1550nm, 50nm BW"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="1550nm, 50nm BW")
        ENDIF

    ELIF "$SLOT" == "J"
        IF @mystatus == "J-band"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="J-band")
        ENDIF

    ELIF "$SLOT" == "H"
        IF @mystatus == "H-band"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="H-band")
        ENDIF

    ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
