:Header
    OBE_ID=SCEXAO
    OBE_MODE=INFRA_RED
    COMMAND=MKIDS_PICKOFF
    Script_ID=INFRA_RED01
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/05

:Parameter
    SLOT=MIRROR
    *SLOT=ARWINDOW,MIRROR,T10R90,T90R10,1.35UMSP

:Command

:start

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="MEC Pickoff Slot Change" ObsInfo2=Clear ObsInfo3="CMD: Slot=$SLOT" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$SLOT" == "ARWINDOW"
        EXEC SCEXAO MKIDS_PICKOFF SLOT=$SLOT;
        EXEC OBS CHECK_STATUS MODE=AND TIMEOUT=15 C1=[SCX.MKIDS.PKO EQ "AR window"];
        Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Slot= !SCX.MKIDS.PKO";
    *ELIF "$SLOT" == "MIRROR"
        EXEC SCEXAO MKIDS_PICKOFF SLOT=$SLOT;
        EXEC OBS CHECK_STATUS MODE=AND TIMEOUT=15 C1=[SCX.MKIDS.PKO EQ "Gold mirror"];
        Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Slot= !SCX.MKIDS.PKO";
    *ELIF "$SLOT" == "T10R90"
        EXEC SCEXAO MKIDS_PICKOFF SLOT=$SLOT;
        EXEC OBS CHECK_STATUS MODE=AND TIMEOUT=15 C1=[SCX.MKIDS.PKO EQ "T10/R90"];
        Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Slot= !SCX.MKIDS.PKO";
    *ELIF "$SLOT" == "T90R10"
        EXEC SCEXAO MKIDS_PICKOFF SLOT=$SLOT;
        EXEC OBS CHECK_STATUS MODE=AND TIMEOUT=15 C1=[SCX.MKIDS.PKO EQ "T90/R10"];
        Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Slot= !SCX.MKIDS.PKO";
    *ELIF "$SLOT" == "1.35UMSP"
        EXEC SCEXAO MKIDS_PICKOFF SLOT=$SLOT;
        EXEC OBS CHECK_STATUS MODE=AND TIMEOUT=15 C1=[SCX.MKIDS.PKO EQ "J-band dichiro"];
        Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Slot= !SCX.MKIDS.PKO";
    *ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
