:Header
    OBE_ID=SCEXAO
    OBE_MODE=INFRA_RED
    COMMAND=PALILA_PARAMETERS
    Script_ID=INFRA_RED14
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/10

:Parameter
    NDR=NOP
    *NDR=1,2,4,8,16,32,64,128,255

:Command
:start

################################
# UNIMPLEMENTED COMMAND
################################

# local function
def execute_command(comparison){
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Changing...";

    EXEC SCEXAO PALILA_PARAMETERS NDR=$NDR;

#    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="status alias" COMPARISON1="@comparison";

    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: NDR=$NDR";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="PALILA Parameters Change" ObsInfo2=Clear ObsInfo3="CMD: NDR=$NDR" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$NDR" == "1"

        # must assign to variable to excetue local function
        # fill in 'none' with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    *ELIF "$NDR" == "2"

        # must assign to variable to excetue local function
        # fill in 'none' with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    *ELIF "$NDR" == "4"

        # must assign to variable to excetue local function
        # fill in 'none' with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    *ELIF "$NDR" == "8"

        # must assign to variable to excetue local function
        # fill in 'none' with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    *ELIF "$NDR" == "16"

        # must assign to variable to excetue local function
        # fill in 'none' with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")


    *ELIF "$NDR" == "32"

        # must assign to variable to excetue local function
        # fill in 'none' with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")


    *ELIF "$NDR" == "64"

        # must assign to variable to excetue local function
        # fill in 'none' with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")


    *ELIF "$NDR" == "128"

        # must assign to variable to excetue local function
        # fill in 'none' with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")


    *ELIF "$NDR" == "256"

        # must assign to variable to excetue local function
        # fill in 'none' with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")


    *ENDIF
:main_end

#Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
