:Header
    OBE_ID=SCEXAO
    OBE_MODE=VISIBLE
    COMMAND=DM_OFFLOAD
    Script_ID=VISIBLE08
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/13

:Parameter
    STATE=OFF
    *STATE=ON,OFF

:Command
:start

#####################################
# WARNING: MISSING STATUS ALIAS 
#####################################

# local function
def execute_command(comparison){
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Changing...";

    EXEC SCEXAO DM_OFFLOAD STATE=$STATE;

#    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="status alias" COMPARISON1="@comparison";
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: State= !status alias";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="Changing DM Offload State" ObsInfo2=Clear ObsInfo3="CMD: State=$STATE" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$STATE" == "ON"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="ON")

    *ELIF "$STATE" == "OFF"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="OFF")

    *ENDIF
:main_end

#Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
