:Header
    OBE_ID=SCEXAO
    OBE_MODE=VISIBLE
    COMMAND=LOOP
    Script_ID=VISIBLE01
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/14

# ask olivier for default
:Parameter
    STATE=OPEN
    *STATE=CLOSE,OPEN,ZERO

:Command
:start

# import
from "SCEXAO_Helpers" import strip
# status with no following spaces
asn mystatus = @strip("!SCX.PYWFS.LOOP")

##############################
# STATUS ALIAS DISFUNCTIONAL
##############################

# local function
def execute_command(comparison){
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Changing...";

    EXEC SCEXAO LOOP STATE=$STATE;

#    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.PYWFS.LOOP" COMPARISON1="@comparison";

    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: State= $STATE";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="Changing PyWFS Loop Status" ObsInfo2=Clear ObsInfo3="CMD: State=$STATE" ObsInfo4=Clear ObsInfo5=Clear;

:main_start

#    IF @mystatus == "$STATE"
#        Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
#        Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
#    ELSE
        # must assign to variable to excetue local function
    asn why_do_I_exist = @execute_command(comparison="$STATE")
#    ENDIF

:main_end

#Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
