:Header
    OBE_ID=SCEXAO
    OBE_MODE=VISIBLE
    COMMAND=LOOP
    Script_ID=VISIBLE01
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/14

:Parameter
    STATE=NOP
    *STATE=CLOSE,OPEN,ZERO

:Command
:start

# this loop function checks for changes in the pywfs loop (make sure this is what the LOOP command does)

# local function
def execute_command(comparison){
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Changing...";
    EXEC SCEXAO LOOP STATE=$STATE;
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.PYWFS.LOOP" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: State= !SCX.PYWFS.LOOP";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="Changing PyWFS Loop Status" ObsInfo2=Clear ObsInfo3="CMD: State=$STATE" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$STATE" == "CLOSE"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="CLOSE")

    *ELIF "$STATE" == "OPEN"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="OPEN")

    *ELIF "$STATE" == "ZERO"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="ZERO")

    *ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
