:Header
    OBE_ID=SCEXAO
    OBE_MODE=VISIBLE
    COMMAND=PYWFS_FILTER
    Script_ID=VISIBLE02
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/11

:Parameter
    SLOT=OPEN
    *SLOT=OPEN,BLOCK

:Command
:start

# local function
def execute_command(comparison){
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Changing...";
    EXEC SCEXAO PYWFS_FILTER SLOT=$SLOT;
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.PYWFS.FLT" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Slot= !SCX.PYWFS.FLT";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="Changing PyWFS Filter" ObsInfo2=Clear ObsInfo3="CMD: Slot=$SLOT" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$SLOT" == "OPEN"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="OPEN")

    *ELIF "$SLOT" == "BLOCK"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="BLOCK")

    *ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
