:Header
    OBE_ID=SCEXAO
    OBE_MODE=VISIBLE
    COMMAND=SET_MULT_FACTOR
    Script_ID=VISIBLE09
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/13

:Parameter
    FACTOR=NOP

:Command
:start

#####################################
# WARNING: MISSING STATUS ALIAS
#####################################

# local function
def execute_command(x){
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Changing...";

    EXEC SCEXAO SET_MULT_FACTOR FACTOR=$FACTOR;

#    EXEC SCEXAO CHECK_STATUS_CHANGED TIMEOUT=100 STATUS_VAR="status alias";
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: Factor= !status alias";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="Changing Multiplication Factor" ObsInfo2=Clear ObsInfo3="CMD: Factor=$FACTOR" ObsInfo4=Clear ObsInfo5=Clear;

:main_start

    # must assign to variable to excetue local function
    asn why_do_I_exist = @execute_command(x="NA")

:main_end

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
