:Header
    OBE_ID=SCEXAO
    OBE_MODE=VISIBLE
    COMMAND=SET_PYWFS_LOOP_GAIN
    Script_ID=VISIBLE06
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/11

:Parameter
    GAIN=NOP

:Command
:start

# import
from "SCEXAO_Helpers" import strip
# status with no following spaces
asn mystatus = @strip("!SCX.PYWFS.GAIN")

##############################
# STATUS ALIAS DISFUNCTIONAL
##############################

# local function
def execute_command(comparison){
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Changing...";

    EXEC SCEXAO SET_PYWFS_LOOP_GAIN GAIN=$GAIN;

#    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.PYWFS.GAIN" COMPARISON1="@comparison";

    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: Gain= $GAIN";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="Changing PyWFS Loop Gain" ObsInfo2=Clear ObsInfo3="CMD: Gain=$GAIN" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
#    IF @mystatus == "$GAIN"
#        Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
#        Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
#    ELSE
        # must assign to variable to excetue local function
    asn why_do_I_exist = @execute_command(comparison="$GAIN")
#    ENDIF

:main_end

#Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
