:Header
    OBE_ID=SCEXAO
    OBE_MODE=SETUP
    COMMAND=OAP1
    Script_ID=SETUP02
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/05

:Parameter
    STATE=OFF
    *STATE=ON,OFF
    AMPLITUDE=NOP
    MODE=IMAGING
    *MODE=PDI,IMAGING

:Command
:start

# local function
def execute_command(comparison){
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.GRID.STAT" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: State= !SCX.GRID.STAT";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="Changing ASTROGRID" ObsInfo2=Clear ObsInfo3="CMD: State=$STATE" ObsInfo4=Clear ObsInfo5=Clear;

# ADVISORY: only checks when the state and amplitude changes, mode change verification is as of yet unimplemented

:main_start

    # send command
    EXEC SCEXAO ASTROGRID STATE=$STATE AMPlITUDE=$AMPLITUDE MODE=$MODE;

    # change the screen
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo4=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Changing...";
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo4="Changing...";

    # state check
    *IF "$STATE" == "OFF"
        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="OFF")
    *ELIF "$STATE" == "ON"
        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="ON")
    *ENDIF

    # amplitude check
    asn amplitude = $AMPLITUDE / 1000
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.GRID.AMP" COMPARISON1="@amplitude";
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo4=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo4="Result: Amplitude= !SCX.GRID.AMP";


:main_end

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
