:Header
    OBE_ID=SCEXAO
    OBE_MODE=SETUP
    COMMAND=OAP1
    Script_ID=SETUP02
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/05

:Parameter
    POSITION=INT
    *POSITION=INT,CWFS,NIRWFS

:Command
:start

# local function
def execute_command(comparison){
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Changing...";
    EXEC SCEXAO OAP1 SLOT=$SLOT;
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.OAP1" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Slot= !SCX.OAP1";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="Changing OAP1" ObsInfo2=Clear ObsInfo3="CMD: Position=$POSITION" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$POSITION" == "CWFS"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="AO188-CWFS")

    *ELIF "$POSITION" == "NIRWFS"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="AO3k-NIRWFS")

    *ELSE

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="INT")

    *ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
