:Header
    OBE_ID=SCEXAO
    OBE_MODE=SETUP
    COMMAND=OAP1
    Script_ID=SETUP02
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/05

:Parameter
    POSITION=INT
    *POSITION=INT,CWFS,NIRWFS

:Command
:start

from "Helpers" import strip

# local function
def execute_command(comparison){
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Changing...";
    EXEC SCEXAO OAP1 POSITION=$POSITION;
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.OAP1" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: Position= !SCX.OAP1";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="Changing OAP1" ObsInfo2=Clear ObsInfo3="CMD: Position=$POSITION" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    asn status = @strip("!SCX.OAP1")
    *IF "$POSITION" == "CWFS"
        *IF @status == "AO188-CWFS"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        *ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="AO188-CWFS")
        *ENDIF

    *ELIF "$POSITION" == "NIRWFS"
        *IF @status == "AO3k-NIRWFS"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        *ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="AO3k-NIRWFS")
        *ENDIF

    *ELIF "$POSITION" == "INT"
        *IF @status == "INT"
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
            Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Already in Position";
        *ELSE
            # must assign to variable to excetue local function
            asn why_do_I_exist = @execute_command(comparison="INT")
        *ENDIF

    *ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
