:Header
    OBE_ID=SCEXAO
    OBE_MODE=SETUP
    COMMAND=OAP1
    Script_ID=SETUP02
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/05

:Parameter
    POSITION=INT
    *POSITION=INT,CWFS,NIRWFS

:Command

:start

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="TESTING OAP1" ObsInfo2=Clear ObsInfo3="CMD: Position=$POSITION" ObsInfo4=Clear ObsInfo5=Clear 

:main_start
    *IF "$POSITION" == "CWFS"
        EXEC SCEXAO OAP1 POSITION=$POSITION;
        EXEC OBS CHECK_STATUS MODE=AND TIMEOUT=10 C1=[!SCX.OAP1 EQ "AO188-CWFS"];
        Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Position= !SCX.OAP1";
    *ELIF "$POSITION" == "NIRWFS"
        EXEC SCEXAO OAP1 POSITION=$POSITION;
        EXEC OBS CHECK_STATUS MODE=AND TIMEOUT=10 C1=[!SCX.OAP1 EQ "AO3k-NIRWFS"];
        Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Position= !SCX.OAP1";
    *ELSE
        EXEC SCEXAO OAP1 POSITION=$POSITION;
        EXEC OBS CHECK_STATUS MODE=AND TIMEOUT=10 C1=[!SCX.OAP1 EQ $POSITION];
        Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Position= !SCX.OAP1";
    *ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
