:Header
    OBE_ID=SCEXAO
    OBE_MODE=SETUP
    COMMAND=SCEXAO_DM
    Script_ID=SETUP01
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/05

:Parameter
    STATE=PINHOLES
    *STATE=FLAT,ZERO,PINHOLES

###############################
# WITHOUT STATUS ALIAS
###############################

:Command
:start

# local function
def execute_command(comparison){
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Changing...";

    EXEC SCEXAO SCEXAO_DM STATE=$STATE;

#    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="status alias" COMPARISON>
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: State= !status alias";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="SCEXAO DM" ObsInfo2=Clear ObsInfo3="CMD: State=$STATE" ObsInfo4=Clear ObsInfo5=Clear; 
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="SCEXAO DM State Change" ObsInfo2=Clear ObsInfo3="CMD: State=$STATE" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$STATE" == "J"

        # must assign to variable to excetue local function
        # 'none' to be filled in with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    *ELIF "$STATE" == "H"

        # must assign to variable to excetue local function
        # 'none' to be filled in with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    *ELIF "$STATE" == "K"

        # must assign to variable to excetue local function
        # 'none' to be filled in with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    *ELIF "$STATE" == "OUT"

        # must assign to variable to excetue local function
        # 'none' to be filled in with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    *ENDIF
:main_end

#Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
