:Header
    OBE_ID=SCEXAO
    OBE_MODE=SETUP
    COMMAND=SET_MODE
    Script_ID=SETUP05
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/11

:Parameter
    MODE=NOP
    *MODE=CHARIS,CHARISPDI,CHARISPDI+FPDI,REACH

###############################
# WITHOUT STATUS ALIAS
###############################

:Command
:start

# local function
def execute_command(comparison){

    EXEC SCEXAO SET_MODE MODE=$MODE;

    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: Mode= !$MODE";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="Set Mode" ObsInfo2=Clear ObsInfo3="CMD: MODE=$MODE" ObsInfo4=Clear ObsInfo5=Clear;

:main_start

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="none")

:main_end

#Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
