:Header
    OBE_ID=SCEXAO
    OBE_MODE=SETUP
    COMMAND=SET_MODE
    Script_ID=SETUP05
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/11

:Parameter
    MODE=NOP
    *MODE=CHARIS,CHARISPDI,CHARISPDI+FPDI,REACH

###############################
# WITHOUT STATUS ALIAS
###############################

:Command
:start

# local function
def execute_command(comparison){
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Changing...";

    EXEC SCEXAO SET_MODE MODE=$MODE;

#    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="status alias" COMPARISON1="@comparison";

    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Position= !$POSITION";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="Set Mode" ObsInfo2=Clear ObsInfo3="CMD: MODE=$MODE" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$MODE" == "CHARIS"

        # must assign to variable to excetue local function
        # replace 'none' with value of status alias 
        asn why_do_I_exist = @execute_command(comparison="none")

    *ELIF "$MODE" == "CHARISPDI"

        # must assign to variable to excetue local function
        # replace 'none' with value of status alias 
        asn why_do_I_exist = @execute_command(comparison="none")

    *ELIF "$MODE" == "CHARISPDI+FPDI"

        # must assign to variable to excetue local function
        # replace 'none' with value of status alias  
        asn why_do_I_exist = @execute_command(comparison="none")

    *ELIF "$MODE" == "REACH"

        # must assign to variable to excetue local function
        # replace 'none' with value of status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    *ENDIF
:main_end

#Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
