:Header
    OBE_ID=SCEXAO
    OBE_MODE=SETUP
    COMMAND=SHUTDOWN_SCEXAO
    Script_ID=SETUP04
    Script_Version=2.0
    Script_Author=Axel
    Script_Update=2026/08/14

:Parameter
# button

:Command
:start

# local function
def execute_shutdown(){
# start text
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Shutting down...";

# commands    
    EXEC SCEXAO LOOP STATE="OPEN";
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.PYWFS.LOOP" COMPARISON1="OPEN";
    EXEC SCEXAO LOOP STATE="ZERO";
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.PYWFS.LOOP" COMPARISON1="ZERO";
    EXEC SCEXAO PYWFS_GAIN EM_GAIN="1";
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.PYWFS.GAIN" COMPARISON1="1";
    EXEC SCEXAO SETUP_PYWFS FREQUENCY="1000" MOD_AMP="0.1";
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.PYWFS.FREQ" COMPARISON1="1000";
    # ask about mod. amp. check
    EXEC SCEXAO PYWFS_FILTER SLOT="BLOCK";
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.PYWFS.FLT" COMPARISON1="BLOCK";
    EXEC SCEXAO WFS_ACQUISITION MODE="STOP";
    # no status

# end text
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Shutdown complete";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="Shutting-down SCExAO";

:main_start

    # must assign to variable to excetue local function
    asn why_do_I_exist = @execute_shutdown()

:main_end

:end
