:Header
    OBE_ID=SCEXAO
    OBE_MODE=SETUP
    COMMAND=SRC_FIB
    Script_ID=SETUP04
    Script_Version=1.0
    Script_Author=Axel Reid
    Script_Update=2026/08/10

:Parameter
    POSITION=OUT
    *POSITION=IN,OUT,PINHOLE

:Command
:start

# local function
def execute_command(comparison){
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Changing...";
    EXEC SCEXAO SRC_FIB POSITION=$POSITION;
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.SRC.FIB" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo3="Result: Position= !SCX.SRC.FIB";
}

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo1="Source Fiber Change" ObsInfo2=Clear ObsInfo3="CMD: Position=$POSITION" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$POSITION" == "IN"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="IN")

    *ELIF "$POSITION" == "OUT"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="OUT")

    *ELIF "$POSITION" == "PINHOLE"

        # must assign to variable to excetue local function
        asn why_do_I_exist = @execute_command(comparison="PINHOLE MASK")

    *ENDIF
:main_end

Exec OBS Set_Message Instrument_Name=!FITS.SBR.MAINOBCP ObsInfo2="Done";

:end
