:Header
    OBE_ID=SCEXAO
    OBE_MODE=SETUP
    COMMAND=SRC_FLUX
    Script_ID=SETUP07
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/11

:Parameter
    MODE=DEFAULT
    *MODE=DEFAULT,CHARIS,MIN

:Command
:start

######################################
# WITHOUT STATUS ALIAS
######################################

# local function
def execute_command(comparison){
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Changing...";

    EXEC SCEXAO SRC_FLUX MODE=$MODE;

#    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.SRC.FLUX.FLT" COMPARISON1="@comparison";
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Mode= $MODE";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="Changing Source Flux" ObsInfo2=Clear ObsInfo3="CMD: Mode=$MODE" ObsInfo4=Clear ObsInfo5=Clear;

:main_start

    # must assign to variable to excetue local function
    asn why_do_I_exist = @execute_command(comparison="none")

:main_end

#Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
