:Header
    OBE_ID=SCEXAO
    OBE_MODE=SETUP
    COMMAND=STARTUP_SCEXAO
    Script_ID=SETUP10
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/14

:Parameter
    MODE=NOP
    *MODE=CALIBRATION,ON-SKY

:Command
:start

# local function
def execute_on-sky(){
# start text
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Setting-up on-sky...";

# commands    
    EXEC SCEXAO WFS_ACQUISITION MODE="START";
    # no status
    EXEC SCEXAO PYWFS_FILTER SLOT="OPEN";
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.PYWFS.FLT" COMPARISON1="OPEN";
    EXEC SCEXAO SETUP_PYWFS FREQUENCY="1000" MOD_AMP="0.4";
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.PYWFS.FREQ" COMPARISON1="1000";
    # ask about mod. amp. check
    EXEC SCEXAO PYWFS_GAIN EM_GAIN="1";
    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="SCX.PYWFS.GAIN" COMPARISON1="1";

# end text
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Setup complete";
}

def execute_calibration(){
    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="ERROR: Command unimplemented";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="Starting-up SCExAO" ObsInfo2=Clear ObsInfo3="CMD: Mode=$MODE" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$MODE" == "CALIBRATION"

        # must assign to variable to excetue local function
        # replace 'none' with the value of the status alias  
        asn why_do_I_exist = @execute_calibration()

    *ELIF "$MODE" == "ON-SKY"

        # must assign to variable to excetue local function
        # replace 'none' with the value of the status alias
        asn why_do_I_exist = @execute_on-sky()
        Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

    *ENDIF

:main_end

:end
