:Header
    OBE_ID=SCEXAO
    OBE_MODE=SETUP
    COMMAND=STARTUP_SCEXAO
    Script_ID=SETUP10
    Script_Version=1.0
    Script_Author=Axel
    Script_Update=2026/08/14

:Parameter
    MODE=NOP
    *MODE=CALIBRATION,ON-SKY

:Command
:start

#############################
# MISSING STATUS ALIAS
#############################

# local function
def execute_command(comparison){
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Changing...";

    EXEC SCEXAO STARTUP_SCEXAO MODE=$MODE;

#    EXEC SCEXAO CHECK_STATUS TIMEOUT_COUNTER=100 CONDITION="EQUALS" STATUS_VAR1="status alias" COMPARISON1="@comparison";
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3=Clear;
#    Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo3="Result: Mode= !status alias";
}

Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1=Clear ObsInfo2=Clear ObsInfo3=Clear ObsInfo4=Clear ObsInfo5=Clear;
Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo1="Starting-up SCExAO" ObsInfo2=Clear ObsInfo3="CMD: Mode=$MODE" ObsInfo4=Clear ObsInfo5=Clear;

:main_start
    *IF "$MODE" == "CALIBRATION"

        # must assign to variable to excetue local function
        # replace 'none' with the value of the status alias  
        asn why_do_I_exist = @execute_command(comparison="none")

    *ELIF "$MODE" == "ON-SKY"

        # must assign to variable to excetue local function
        # replace 'none' with the value of the status alias
        asn why_do_I_exist = @execute_command(comparison="none")

    *ENDIF
:main_end

#Exec OBS Set_Message Instrument_Name=SCEXAO ObsInfo2="Done";

:end
